### ISSUE TITLE
Expected disk write rate.

### ISSUE THREAD

**Issue by btrepp** [k3s-io/kine#105]
Hi all,

Just wondering how much diskio would be expected from a two server setup?.

When I inspect my Nas, with mariadb. It seems to sit pretty constant at 5mb/sec write. Is this normal or high?.

When running on things like raspberry pis, you can wear out SD cards and the like. Is the disk usage similar for single server and sqllite?

**Comment by brandond** [comment]
It depends heavily on what your cluster is doing. The more you write to the Kubernetes apiserver (and just running nodes causes some amount of writes for health checks and leases) the higher the data store throughout.

Have you seen https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/resource-profiling/ ?

**Comment by brandond** [comment]
Also, this probably belongs as a k3s Q/A discussion, not an issue here.

**Comment by btrepp** [comment]
Thanks for that. I think my cluster is in a funky state from that. Have created a discussion for it and will close this one.
