### ISSUE TITLE
Vault backend

### ISSUE THREAD

**Issue by FruityWelsh** [k3s-io/kine#107]
Since Vault's key-value store is API based would a [vault](https://www.vaultproject.io/) driver backend be possible/easy?

**Comment by FruityWelsh** [comment]
I believe vault's key-value V2 does versioning on the values if this is the same [thing](https://learn.hashicorp.com/tutorials/vault/versioned-kv?in=vault/secrets-management) as Multiversion Concurrency Control (MVCC) .

**Comment by brandond** [comment]
Hmm, in that case you might just look into using Vault as the KMS for the Kubernetes secrets-encryption provider, instead of trying to use it behind an etcd translation layer.

**Comment by FruityWelsh** [comment]
For sure, just seemed like a potential complexity reduction, rather than two key-value services running on the same cluster. 
There is already some work for the reverse as well, to use etcd as a storage backend to vault, but obviously there would be some issue then using vault to encrypt entries in etcd that aren't being served by vault...

**Comment by FruityWelsh** [comment]
And of course overhead reduction, which would help in resource constrained envs

**Comment by FruityWelsh** [comment]
You can run Vault with an internal Raft storage in a HA setup. I would agree that this is more complex than just ETCD. It's more a complexity reduction is compared to a Kubernetes deployment of Vault with embedded Raft storage. Currently, to use both ETCD and Vault, you end up with two different Raft storage that both need their encryption backends managed. So currently for Vault to come up it is dependent on ETCD and therefor an internal Vault cluster is not usable as the KMS service of ETCD, so it required to be an external cluster.

With a converged one, you're able to have an encrypted ETCD backend with a variety of ways to unseal (shamir key ceremony, HSM, and another external KMS).
