### ISSUE TITLE
The boundary of Kine (or K3S) compared with K8S

### ISSUE THREAD

**Issue by Steamgjk** [k3s-io/kine#120]
IIUC, Kine can be regarded as a shim layer (or an adaptor) which enables the replacement of etcd with other storage backend. 
I know etcd is much heavier and provides tons of APIs. I am just not sure:
(1) What etcd APIs are used by Kubenetes?
(2) Among the APIs used by Kubenetes, which have been covered (hooked) by Kine? Which have not been hooked by Kine? 

Do you staff have a list of the etcd APIs used by Kubenete and the list of etcd APIs that have already been covered by Kine? I think that will be very helpful for us to understand the boundary of K3S (i.e. which K8S can do but K3S may suffer from problems)
Thanks

**Comment by brandond** [comment]
> Among the APIs used by Kubenetes, which have been covered (hooked) by Kine?

https://github.com/k3s-io/kine/blob/dc877c3e2003aa6e01f1e35a09a6fb2578aa8a6e/pkg/server/server.go#L23-L33

**Comment by Steamgjk** [comment]
> > Among the APIs used by Kubenetes, which have been covered (hooked) by Kine?
> 
> https://github.com/k3s-io/kine/blob/dc877c3e2003aa6e01f1e35a09a6fb2578aa8a6e/pkg/server/server.go#L23-L33


Thanks for the pointer @brandond. A follow-up question is: What etcd APIs used by Kubernete by not supported by Kine?  (I ask this question because I want to understand under what scenarios K8S can work but K3S may be cautious)

**Comment by brandond** [comment]
None of them. If they were required by Kubernetes and we didn't implement them, then kine wouldn't be very usable, would it.

**Comment by Steamgjk** [comment]
> None of them. If they were required by Kubernetes and we didn't implement them, then kine wouldn't be very usable, would it.

So you are saying, Kine has covered **all** the etcd APIs needed by Kubernete?
That is great if it is this case!

**Comment by brandond** [comment]
Yes, that's why it works.

**Comment by Steamgjk** [comment]
> Yes, that's why it works.

Awesome! I like this project and I will take a deep dive into it.  Thanks!
