### ISSUE TITLE
Vitess

### ISSUE THREAD

**Issue by kfox1111** [k3s-io/kine#152]
Anyone try kine against a vitess cluster?

**Comment by brandond** [comment]
not that I'm aware of, but in my experience anything that does sharded multi-master clustering won't work well.

**Comment by kfox1111** [comment]
Might be an interesting use case to test, as vcluster/k3s usage grows, and having one, scaleable mysql cluster behind all the tenant clusters could make management easier.

**Comment by kfox1111** [comment]
Its not multi-master by design: https://vitess.io/docs/15.0/overview/scalability-philosophy/

So, it may not be a problem there. The sql schema seems pretty simplistic. If a cluster name property was added to the schema, you might not even need separate databases for multiple instances and could shard on it?

**Comment by l2dy** [comment]
Vitess [fails](https://github.com/vitessio/vitess/blob/71cd149b57652d80a123d1dd326a4bde6051afab/go/vt/vtgate/engine/dbddl_plugin.go#L52) `CREATE DATABASE` queries by default, which makes Kine incompatible with some managed database providers.

https://github.com/k3s-io/kine/blob/c5f2d892d70778fb9ad15208d4ca8617c3c794da/pkg/drivers/mysql/mysql.go#L46
