### ISSUE TITLE
question: in mysql, GetRevisionAfterSQL sql will return empty when subquery return null value

### ISSUE THREAD

**Issue by wangyanphp** [k3s-io/kine#186]
![image](https://github.com/k3s-io/kine/assets/13374363/d652aca6-d286-4260-a44a-ed57b7220699)
when this subquery return null( there is no selected rows), the where clause will become "mkv.id > NULL", it's the expected behavior?

**Comment by brandond** [comment]
Yes? Is there a problem?

**Comment by brandond** [comment]
Are you sure you're calling it with valid options? Where did you get the revision from?

**Comment by wangyanphp** [comment]
yes, i used a non-existent key, my request is:
```
		key := "/registry"
		opts = []clientv3.OpOption{clientv3.WithLimit(1000), clientv3.WithRev(357286)}
		rangeEnd := clientv3.GetPrefixRangeEnd(key)
		opts = append(opts, clientv3.WithRange(rangeEnd))
```

the key "/registry" doesn't exist

**Comment by brandond** [comment]
Kine intentionally implements only the bits of etcd that Kubernetes uses. If Kubernetes doesn't make calls in that same way, it's likely that kine does not implement that functionality. Can you get the desired behavior out of a real etcd server, given the same keys and client calls?

**Comment by wangyanphp** [comment]
> Kine intentionally implements only the bits of etcd that Kubernetes uses. If Kubernetes doesn't make calls in that same way, it's likely that kine does not implement that functionality. Can you get the desired behavior out of a real etcd server, given the same keys and client calls?

yes, Kubernetes doesn't make calls in that way. i'm migrating data from etcd to kine using etcdctl make-mirror tool. I can get the desired behavior out of a real etcd server with the same key and options. And i also can get the desired behavior from kine when i added COALESCE function in "idOfKey" sql:
```
	idOfKey = `
		AND
		mkv.id <= ? AND
		mkv.id > COALESCE((
			SELECT MAX(ikv.id) AS id
			FROM kine AS ikv
			WHERE
				ikv.name = ? AND
				ikv.id <= ?), 0)`
```

**Comment by brandond** [comment]
K3s itself has a kine -> etcd function built in, you can find it at:
https://github.com/k3s-io/k3s/blob/213d7ad499e166290872f51c63d8eaa2f1fe78b3/pkg/etcd/etcd.go#LL740C2-L740C2
