### ISSUE TITLE
How to enable TLS connection for Kine

### ISSUE THREAD

**Issue by shihaoH** [k3s-io/kine#195]
I only want to enable certificate verification for the Kine connection, but I don't need to enable TLS for connecting to MySQL.

**Comment by brandond** [comment]
Do you only want to have Kine enable TLS on its listener? Or do you want to both enable TLS, and require client certificate authentication?

At the moment, kine does support TLS, via the `--server-cert-file` and `--server-key-file` options. It does not support client certificate authentication.
