### ISSUE TITLE
Bug: Image manifest not pushed since v0.9.8

### ISSUE THREAD

**Issue by tamalsaha** [k3s-io/kine#199]
https://hub.docker.com/r/rancher/kine/tags

Since v0.9.8, the image manifest is not pushed. I am guessing this is not intentional. Can you push the missing manifests:

- rancher/kine:v0.9.9
- rancher/kine:v0.10.0
- rancher/kine:v0.10.1

**Comment by brandond** [comment]
No, I can't, but I can fix the automation and tag a new release.

**Comment by brandond** [comment]
Broken by drone dropping support for 32bit arm:
https://drone-publish.k3s.io/k3s-io/kine/68/3/3

**Comment by tamalsaha** [comment]
I don't have any context here. If 32bit arm is not building, may be drop that one and cut a new release? That will be much appreciated!

**Comment by brandond** [comment]
You can use the arch-specific tags, it's just that the manifest list isn't pushed unless all of the architectures successfully push their tags.

[rancher/kine:v0.10.1-amd64](https://hub.docker.com/layers/rancher/kine/v0.10.1-amd64/images/sha256-bd680b85df70018468f61e81943a9cc80d4cdeccbb0580b1cd0e9b6ef6d05ad5?context=explore) for example.

**Comment by brandond** [comment]
Latest tag (v0.10.2) should be set.
