### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by litcc** [k3s-io/kine#203]
When I add the parameter `?compress=true` parameter to the cluster database url, the program reports the following error:

```
starting kubernetes: preparing server: creating storage endpoint: building kine: compression not implemented yet
```

I noticed that compression has not yet been implemented in the Kine project. 

Is there any intention to support this feature in the project's follow-up? Compression is very useful to reduce the amount of data transferred over the network, especially in multi-cloud Kubernetes clusters.

**Comment by brandond** [comment]
What database are you using? That error isn't coming from kine itself, so I suspect compression support is missing from the actual golang database driver.

**Comment by litcc** [comment]
I am currently using mysql8.0 database, the driver used should be https://github.com/go-sql-driver/mysql, is it because the driver does not implement the compression feature that causes the error?

**Comment by brandond** [comment]
Yes: https://github.com/go-sql-driver/mysql/blob/0b18dac46f7f10d00411ab6fb10b8d6e4522c2d9/dsn.go#L468-L469

I'm going to close this, as it is an issue with the driver, not kine.
