### ISSUE TITLE
Please document how to run the tests locally without drone CI

### ISSUE THREAD

**Issue by oz123** [k3s-io/kine#239]
I am trying to figure out the right order of running the scripts for testing, under script.
It seems the I can use `drone.yml` as a guidance. However, some variables seem supplied by the drone-ci environemen.

**Comment by oz123** [comment]
Would you accept a PR for adding these steps as targets in the Makefile?
```
docker build -t kine:test-<git-hash> -f Dockerfile.test .
docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache --privileged kine:test--<git-hash>"./scripts/test sqlite"
````

**Comment by brandond** [comment]
You need to set the environment variables (`-e ARCH` and so on) to the correct values.

**Comment by oz123** [comment]
Can we add theses as explicit make file targets with proper depencies between the targets?
Or at least a Contributing files explaining this?

**Comment by brandond** [comment]
it would be nice if there were makefile targets, yeah. PR welcome!

**Comment by dereknola** [comment]
This becomes simplier if you just use the [Drone CLI](https://docs.drone.io/cli/install/). Then you can just call 
```
drone exec --trusted --pipeline=amd64 --event=pull-request
```

If you want to just run a single test, use the `--include` flag:
```
drone exec --trusted --pipeline=amd64 --event=pull-request  --include=test-mysql --include=build --include=test-image
```


This will launch all of the DB tests. It runs everything in docker containers on your local machine.

**Comment by s3rj1k** [comment]
> `drone exec --trusted --pipeline=amd64 --event=pull-request`

Does not seem to run the actual tests

**Comment by s3rj1k** [comment]
@brandond `completed` ?

**Comment by s3rj1k** [comment]
For people that will hit the same issue, basic idea of this whole setup should have been working is this:

```
DRONE_COMMIT=$(git rev-parse --short HEAD) drone exec --trusted --pipeline amd64 --event pull_request --include build --include test-image --include test-sqlite .drone.yml
```

But for some unknown reason, in my setup, `/etc/rancher/k3s/k3s.yaml` is not being created inside `k3s-server` container and this makes test fail.

**Comment by brandond** [comment]
We're working on eliminating drone.

**Comment by s3rj1k** [comment]
To run Kubernetes conformance tests manually, one can use `tmux` with 3 tabs, or 3 terminals, like so:

```
# (Console #1): Build and start Kine
make build && \
    rm -f kine.db && \
    ./dist/artifacts/kine-amd64 \
        --endpoint="sqlite://kine.db?cache=shared&mode=rwc" \
        --watch-progress-notify-interval=5s
```

```
# (Console #2): Start K3s server
docker run \
    --interactive \
    --tty \
    --rm \
    --name k3s-server \
    --network host \
    --privileged \
    --env K3S_DEBUG=true \
    --env K3S_DATASTORE_ENDPOINT='http://localhost:2379' \
    docker.io/rancher/k3s:v1.29.4-k3s1 server \
    --kube-apiserver-arg=feature-gates=WatchList=true \
    --disable=coredns,servicelb,traefik,local-storage,metrics-server \
    --disable-network-policy \
    --write-kubeconfig-mode "0644"
```

```
# (Console #3): Run Kubernetes conformance tests (with `fail-fast`)
K8S_VERSION=$(docker exec k3s-server /bin/sh -c "/bin/k3s --version | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+'") && \
    docker cp k3s-server:/etc/rancher/k3s/k3s.yaml ./kubeconfig.yaml && \
    docker run \
        --interactive \
        --tty \
        --rm \
        --network host \
        --volume $(pwd)/kubeconfig.yaml:/root/.kube/config \
        --env "KUBECONFIG=/root/.kube/config" \
        --env "E2E_FOCUS=sig-api-machinery" \
        --env "E2E_SKIP=StorageVersionAPI|Slow|Flaky" \
        --env "E2E_EXTRA_ARGS=--ginkgo.fail-fast" \
        registry.k8s.io/conformance:${K8S_VERSION} \
        /usr/local/bin/kubeconformance

```

launching each command in listed order with some small time waits until output stabilizes.

**Comment by brandond** [comment]
No, why are you disabling everything? I believe conformance requires at least two nodes. It also requires functional cluster dns, why are you disabling everything including coredns?

**Comment by brandond** [comment]
What are your goals here? The test in this repo is mostly just a quick check to make things work. You can look at our CI logs to see that it succeeds. There are conformance tests in K3s CI that you can look at. We also run full certified conformance as part of our release process, and upload the results to CNCF. That is done by our QA team and we don't have public automation for that.

**Comment by s3rj1k** [comment]
> What are your goals here

I am writing custom driver, want to test is, need to understand how to tests properly, this is why I was mentioning testing baseline.

> You can look at our CI logs to see that it succeeds.

Per-commit GHA are only running linter and builder targets in Kine repo.

> There are conformance tests in K3s CI that you can look at.

Can you point me please to relevant place in `k3s` repo?

**Comment by brandond** [comment]
The conformance tests tests should all pass when using a SQL backend. Nats is currently broken. We still have a lot of stuff in Drone, but I believe those logs should be visible to the public.

On the k3s side you can look at the sonobuoy setup scripts in https://github.com/k3s-io/k3s/tree/master/tests/docker

**Comment by s3rj1k** [comment]
> SQL backend

As MySQL or sqlite (was testing sqlite above) also works?

> https://github.com/k3s-io/k3s/tree/master/tests/docker

Took a quite look, they look pretty much same as in `kine`, I wonder how hard it would be to reuse them, for `kine` it took quite a while to untangle those into simple shell commands.

**Comment by brandond** [comment]
As you should be able to see from the files over there, we test sqlite, mysql, and postgres (in addition to embedded etcd).
