### ISSUE TITLE
feat: IAM database authentication

### ISSUE THREAD

**Issue by a7i** [k3s-io/kine#246]
Support IAM database authentication: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

kine only supports username/password or cert-based auth which makes it a bit challenging for organizations with compliance to use short-lived credentials. Supporting IAM database auth eases the rotation and management of credentials.

**Comment by brandond** [comment]
Can you suggest any golang mysql or postgres drivers that support this? It looks fairly non-trivial to enable, as credentials are currently part of the datastore dsn and we leave their extraction up to the driver.

**Comment by a7i** [comment]
Hey @brandond I see, I did not realize that kine just relies on the drivers (it makes sense). So I would need to make the change in this driver: https://github.com/go-sql-driver/mysql

**Comment by brandond** [comment]
and `github.com/jackc/pgx` for postgres

**Comment by a7i** [comment]
Thanks @brandond 🎉 , I'll go ahead and close this Issue then
