### ISSUE TITLE
gRPC health probe on Kine deployment does not work

### ISSUE THREAD

**Issue by yelshall** [k3s-io/kine#252]
It seems that the gRPC server is not working, as when I try to query the server I get back nothing:
```
> grpcurl -plaintext -d '{"service": "kine"}' localhost:2379 grpc.health.v1.Health/Check
Failed to dial target host "localhost:2379": context deadline exceeded
```
This is in the new version (0.11.1) where it seems the [HTTP server was removed](https://github.com/k3s-io/kine/pull/227/files). However, querying the HTTP server in version 0.10.3 seems to be fine.

**Comment by brandond** [comment]
As discussed at https://github.com/kubernetes/kubernetes/pull/118460 the HTTP endpoint is no longer used by Kubernetes for health checking.

The "context deadline exceeded" error doesn't seem to have anything to do with that change though, it sounds to me like kine isn't actually running on that port. Here's what I get:

```
brandond@dev01:~$ ./grpcurl -plaintext -d '{"service": "kine"}' 172.17.0.7:2379 grpc.health.v1.Health/Check
Error invoking method "grpc.health.v1.Health/Check": failed to query for service descriptor "grpc.health.v1.Health": server does not support the reflection API
```

**Comment by brandond** [comment]
I guess this can be left open as a feature request, but I do want to confirm that I don't believe this is necessary to support health checks from clients that already have the `grpc.health.v1.Health` protobuf descriptors available - which would include Kubernetes.

**Comment by brandond** [comment]
I will also note that kine doesn't really do health checks, it will always just respond with `healthpb.HealthCheckResponse_SERVING`
