### ISSUE TITLE
k3s mysql数据库存储kine表

### ISSUE THREAD

**Issue by yujun4464** [k3s-io/kine#260]
mysql数据库提前创建好kine表，再用DML权限帐号连接数据库报错，没权限。请问 k3s mysql连接怎么支持DML权限？

**Comment by brandond** [comment]
K3s always runs a "CREATE DATABASE IF NOT EXISTS" command during startup. If this results in an error, kine will not be able to run. There is not currently any way to disable this behavior; k3s needs permission to run that command.

**Comment by yujun4464** [comment]
如果我提前创建好 kine 表呢？是不是就不需要DDL权限了？但是我尝试了下，提前创建好kine表，还是会报错 Access denied for user

**Comment by yujun4464** [comment]
如果我提前创建好kine表呢？是不是就不需要DDL权限了？我尝试了下，提前创建好kine表，还是会报错 Access Denied for user

**Comment by brandond** [comment]
No. K3s will run the create command regardless of whether or not the database or table already exist.

**Comment by yujun4464** [comment]
有什么办法能解决“无法使用DDL权限，但是又要用mysql 存储 k3s” 这个问题嘛？

**Comment by yujun4464** [comment]
有什么办法能解决“无法使用DDL权限，但是又要用mysql 存储 k3s” 这个问题嘛？

**Comment by brandond** [comment]
No. Give the user the permissions required to run the create statements.
