### ISSUE TITLE
Kubeadm + Kine + NATS possible bug: illegal resource version from storage: 0

### ISSUE THREAD

**Issue by jrovira-kumori** [k3s-io/kine#274]
I have a minimal reproduction of deploying a cluster with Kind (kubeadm) and replacing ETCD with Kine + NATS KV store. It works when Kine uses the default SQLite store (omitting the `--endpoint=...` flag).

Minimal repoduction:
https://github.com/jrovira-kumori/kine-nats-kv-bug-minimal-repro

Running the minimal repoduction you will find that the KubeAPI server is stuck in a loop emitting a high volume of logs stating `illegal resource version from storage: 0`.

The only issue that I have found with a similiar problem is #74 - when using CockroachDB. Not much help here. I have been seriously stuck with this for a while. Any clarification if it is still a WIP feature would be greatly appreciated.

**Comment by brandond** [comment]
What version of kine are you using?

**Comment by brandond** [comment]
cc @bruth

**Comment by jrovira-kumori** [comment]
Thanks for the quick response! Software versions are as follows:

- Kubernetes `v1.29.2`
- Kine `v0.11.4`
- NATS `v2.10.5`

**Comment by jrovira-kumori** [comment]
I have updated the minimal reproduction to make it much easier to follow. 

You can run k3s (with everything disabled **but** the KubeAPI component) and point it to the same Kine. After the initialization is done you can kill k3s and restart the Kubernetes KubeAPI and it now seems to work.

At least the stream of `illegal resource version from storage: 0` no longer appears.

The new minimal reproduction shows this.

**Comment by jrovira-kumori** [comment]
Found the issue. Will publish a PR shortly.
