### ISSUE TITLE
kine periodic query causes MySQL CPU 100% load

### ISSUE THREAD

**Issue by lidh15** [k3s-io/kine#283]
![IMG_2902.HEIC.jpg](https://github.com/k3s-io/kine/assets/14806954/58e8224b-beb4-42df-8091-4a25d887aa96)

the query in the screen shot was executed periodically and caused CPU 100% used
how should I cut this peak usage?

**Comment by brandond** [comment]
That is a pretty normal list query. Queries similar to that one are constantly executed in response to get/list requests. If that is causing your database server to hit 100% cpu utilization, you may need to provide it with more CPU or memory.
