### ISSUE TITLE
Multi-replica Kine

### ISSUE THREAD

**Issue by buji-code** [k3s-io/kine#295]
Hi guys, I'm deploying my in-house multi-control-plane based on vanilla Kubernetes. I thought I could run a Kine container for each control-plane Node, making it fully HA between all apiserver Pods. I notice inconsistent responses when polling the apiserver. This behavior stoped when I scaled my control-plane replicas to 1 (making it a single api-server against a single Kine).

Can Kine run with multiple replicas and ensure correctness at all? If not, does it support a leader-election mechanism?

**Comment by brandond** [comment]
Yes, you can run multiple instances of Kine against a datastore. This is how K3s works when you point multiple servers at a single datastore. Each server runs Kine against the same database, and each server runs an apiserver that talks to the local kine instance.

It should also work fine to point multiple apiservers at a single kine instance, or multiple apiservers at a pool of kine instances. This is not a model that we use, so it probably sees less testing. If you can reproduce any problems, please open an issue describing specifically what you're seeing.
