### ISSUE TITLE
Implement etcd version endpoint

### ISSUE THREAD

**Issue by angelbarrera92** [k3s-io/kine#30]
Hi Rancher team!

I am testing this etcdshin using kubeadm. It works!!!

But every time I use it with kubeadm i have to use the following flag: `--ignore-preflight-errors=ExternalEtcdVersion` because kine seems like does not implement this endpoint.

Is this intended? What version of etcd is implemented? 3.X? I can PR if it should be implemented.

**Comment by ibuildthecloud** [comment]
We only implemented the apis needed by k8s. I'd make the argument that if kubeadm needs the API we should add it. I'd say this is etcd 3.4.  would you be willing to create a PR for this. It should be straight forward because it's a hard coded response.
