### ISSUE TITLE
Don't dump the full SQL payload when `SlowSQLThreshold` is exceeded

### ISSUE THREAD

**Issue by brandond** [k3s-io/kine#305]
The info-level message produced when a query exceeds the `SlowSQLThreshold` duration includes a full dump of the SQL request, including the parameters. This is unnecessarily verbose, and may leak confidential information into the logs. SQL query parameters should only be dumped when logging at Trace level; the log message should not include the payload when printing at lower levels.

**Comment by mezgerj** [comment]
@brandond I took a shot at this in https://github.com/k3s-io/kine/pull/307 . This is my first kine MR so please let me know if anything looks out of place
