### ISSUE TITLE
Changing the RV semantics in Upstream Kubernetes

### ISSUE THREAD

**Issue by nilekhc** [k3s-io/kine#309]
We are codifying the schema of ResourceVersion in upstream Kubernetes with [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/4192-svm-in-tree). 

tl;dr
With this change, we are parsing ResourceVersion to an `int`, thus explicitly defining RV as an integer rather than an opaque string as it is today. Does this affect the project in any way?

**Comment by brandond** [comment]
I think we should be fine - our db schema and interfaces define it as int64:
https://github.com/k3s-io/kine/blob/b6a31549dcc8dee9e893721495e5852b0fa648ae/pkg/logstructured/logstructured.go#L19-L30
