### ISSUE TITLE
About Naming conventions

### ISSUE THREAD

**Issue by 985492783** [k3s-io/kine#310]
Whether key is necessary to use the format of the file directory for naming？

**Comment by brandond** [comment]
What?

**Comment by 985492783** [comment]
after auto-compact, i rebot kine then take error = Failed to list / for revision 1928, because xxx was compact
but when i change all key to "/" + key then take success
![QQ_1721020321944](https://github.com/user-attachments/assets/548014da-060c-46aa-9bf7-df030e7f2ea7)

**Comment by brandond** [comment]
I don't know off the top of my head what the expected behavior is here. Do you see the same behavior from etcd when listing / vs /key for a compacted revision?

**Comment by brandond** [comment]
Kine models the bits of the etcd api that are required for compatibility with Kubernetes. Kubernetes uses the etcd v3 api, but for historical reasons, stores all data in keys that are compatible with the etcd v2 key format:
> etcd uses a file-system-like structure to represent the key-value pairs, therefore all keys start with /.

So this is what kine expects, yes.

**Comment by 985492783** [comment]
get
