### ISSUE TITLE
TTL watch fails if max non-deleted KV revision has been compacted

### ISSUE THREAD

**Issue by 985492783** [k3s-io/kine#311]
my lastest key revision=1999, another key exist such as 1500
if kine auto-compact, the compact revision will be set before 1999, such as 1900
if delete 1999 now my data is
1500 create key value
1999 update key1 value1
2000 delete key value

when i reboot kine, ttlevent will set lastest revision to pre exist key = 1500
![QQ_1721280590209](https://github.com/user-attachments/assets/b7700848-5432-4933-8a9e-714e69441613)
but then lastest < compact and occure error
![QQ_1721280560176](https://github.com/user-attachments/assets/b5c453d5-c0a3-4c9b-bfd5-04bc7982fb52)

**Comment by brandond** [comment]
What is the actual problem here? Please provide specific steps to reproduce.

**Comment by 985492783** [comment]
i cannot reboot kine
![QQ_1721281158139](https://github.com/user-attachments/assets/1789ef8f-0a20-4555-a3c3-066a7c50846d)
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (1, 'compact_rev_key', 1, 0, 0, 2614, 0, 0x, null);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (2, '/registry/health', 1, 0, 0, 0, 0, 0x7B226865616C7468223A2274727565227D, null);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (505, '/one/rsync/123', 0, 0, 3, 504, 0, 0x7265676973746572, 0x7265676973746572);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (1506, '/one/rsync/127.0.0.1', 0, 0, 506, 1505, 0, 0x726567697374657232, 0x726567697374657232);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (1511, '/one/rsync/192.168.2.5', 1, 0, 0, 0, 0, 0x7265676973746572, null);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3600, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3599, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3601, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3600, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3602, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3601, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3603, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3602, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3604, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3603, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3605, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3604, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3606, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3605, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3607, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3606, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3608, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3607, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3609, '/register/one/one-master/11.39.195.56', 0, 0, 1516, 3608, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3610, '/register/one/one-master/11.39.195.56', 0, 1, 1516, 3609, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3611, '/register/one/one-master/11.39.195.56', 1, 0, 0, 3610, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3612, '/register/one/one-master/11.39.195.56', 0, 0, 3611, 3611, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3613, '/register/one/one-master/11.39.195.56', 0, 0, 3611, 3612, 8, 0x, 0x);
INSERT INTO kubernetes.kine (id, name, created, deleted, create_revision, prev_revision, lease, value, old_value) VALUES (3614, '/register/one/one-master/11.39.195.56', 0, 1, 3611, 3613, 8, 0x, 0x);

**Comment by 985492783** [comment]
Please check if it is a bug

**Comment by brandond** [comment]
How **exactly** did you get it into that state? K3s nodes using kine are restarted all the time, and do not experience any problems. These keys are not the standard keys that Kubernetes would create, so I'm assuming you're poking at it directly somehow?

If you're running kine standalone, can you run it with --debug and share the full logs, including logs showing you doing whatever it is that gets it into this state?

**Comment by 985492783** [comment]
revision 3 insert key /a 
revision 4-2500 insert and update key /b
revision 2501 delete /b
wait auto-compact, then compact_rev is large than lastest alive key /a and reboot it will occured error

**Comment by brandond** [comment]
OK, I can reproduce this. tl;dr kine fails to restart properly if there are no non-deleted keys with revisions newer than the compact revision.

I'm curious what specifically you were doing here, doing as the only way to trigger this seems to be to have all non-deleted keys be older than the compact revision, which pretty much never happens with Kubernetes because there are always things that exist and have been updated within the compact interval.

1. start kine with an empty database.
2. create key /a, create and update key /b and update it a bunch, then delete it:
    ```bash
    echo -e "mod(\"/a\") = \"0\"\n\nput /a \"foo\"\n\nget /a\n" | etcdctl txn
    echo -e "mod(\"/b\") = \"0\"\n\nput /b \"bar\"\n\nget /b\n" | etcdctl txn
    for I in {4..2500}; do echo -e "mod(\"/b\") = \"$I\"\n\nput /b \"bar\"\n\nget /b\n" | etcdctl txn; done
    echo -e "mod(\"/b\") = \"2501\"\n\ndel /b\n\nget /b\n" | etcdctl txn
    ```
3. wait for compaction to run twice and move compact_rev up to 1502:
    ```
    INFO[2024-07-22T19:23:37.487868277Z] COMPACT compactRev=2 targetCompactRev=1002 currentRev=2502
    TRAC[2024-07-22T19:23:37.487878137Z] TX COMPACT 1002
    TRAC[2024-07-22T19:23:37.494534997Z] TX SETCOMPACTREVISION 1002
    INFO[2024-07-22T19:23:37.497433675Z] COMPACT deleted 998 rows from 1000 revisions in 9.552161ms - compacted to 1002/2502
    INFO[2024-07-22T19:23:37.497668783Z] COMPACT compactRev=1002 targetCompactRev=1502 currentRev=2502
    TRAC[2024-07-22T19:23:37.497680936Z] TX COMPACT 1502
    TRAC[2024-07-22T19:23:37.501052911Z] TX SETCOMPACTREVISION 1502
    INFO[2024-07-22T19:23:37.501419958Z] COMPACT deleted 500 rows from 500 revisions in 3.736703ms - compacted to 1502/2502
    INFO[2024-07-22T19:23:37.501652573Z] COMPACT revision 1502 has already been compacted
    TRAC[2024-07-22T19:23:37.501682244Z] POSTCOMPACT
    ```
4. Restart kine and notice that the ttl watch blows up:
    ```
    TRAC[2024-07-22T19:26:14.791516889Z] COMPACTSTART
    TRAC[2024-07-22T19:26:14.791572481Z] QUERY [compact_rev_key 0] :  SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name AS thename, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv WHERE kv.name LIKE ? AND kv.id > ? ORDER BY kv.id ASC
    TRAC[2024-07-22T19:26:14.792508986Z] COMPACTSTART len(events)=1
    TRAC[2024-07-22T19:26:14.792574462Z] QUERY [/registry/health  true] :  SELECT * FROM ( SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name AS thename, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv JOIN ( SELECT MAX(mkv.id) AS id FROM kine AS mkv WHERE mkv.name LIKE ? AND mkv.name > ? GROUP BY mkv.name) AS maxkv ON maxkv.id = kv.id WHERE kv.deleted = 0 OR ? ) AS lkv ORDER BY lkv.thename ASC LIMIT 1
    TRAC[2024-07-22T19:26:14.793359517Z] QUERY ROW [] :  SELECT MAX(rkv.id) AS id FROM kine AS rkv
    TRAC[2024-07-22T19:26:14.793443886Z] CREATE /registry/health, size=17, lease=0 => rev=2502, err=rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request
    INFO[2024-07-22T19:26:14.793570205Z] Kine available at http://127.0.0.1:2379
    TRAC[2024-07-22T19:26:14.793731853Z] QUERY [/%  false] :  SELECT * FROM ( SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name AS thename, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv JOIN ( SELECT MAX(mkv.id) AS id FROM kine AS mkv WHERE mkv.name LIKE ? AND mkv.name > ? GROUP BY mkv.name) AS maxkv ON maxkv.id = kv.id WHERE kv.deleted = 0 OR ? ) AS lkv ORDER BY lkv.thename ASC LIMIT 1000
    TRAC[2024-07-22T19:26:14.794791312Z] QUERY [/% /registry/health 2502 false] :  SELECT * FROM ( SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name AS thename, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv JOIN ( SELECT MAX(mkv.id) AS id FROM kine AS mkv WHERE mkv.name LIKE ? AND mkv.name > ? AND mkv.id <= ? GROUP BY mkv.name) AS maxkv ON maxkv.id = kv.id WHERE kv.deleted = 0 OR ? ) AS lkv ORDER BY lkv.thename ASC LIMIT 1000
    TRAC[2024-07-22T19:26:14.795399812Z] QUERY ROW [] :  SELECT MAX(rkv.id) AS id FROM kine AS rkv
    TRAC[2024-07-22T19:26:14.795481095Z] QUERY ROW [] :  SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'
    TRAC[2024-07-22T19:26:14.795586844Z] WATCH /, revision=3
    TRAC[2024-07-22T19:26:14.795629098Z] QUERY ROW [] :  SELECT MAX(rkv.id) AS id FROM kine AS rkv
    TRAC[2024-07-22T19:26:14.795765612Z] QUERY [/% 2] :  SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name AS thename, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv WHERE kv.name LIKE ? AND kv.id > ? ORDER BY kv.id ASC
    TRAC[2024-07-22T19:26:14.795785821Z] QUERY ROW [] :  SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'
    TRAC[2024-07-22T19:26:14.79630364Z] COMPACT starting compactRev=1502 targetCompactRev=2502
    ERRO[2024-07-22T19:26:14.807751924Z] Failed to list / for revision 2: rpc error: code = OutOfRange desc = etcdserver: mvcc: required revision has been compacted
    TRAC[2024-07-22T19:26:14.80778223Z] QUERY ROW [] :  SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'
    TRAC[2024-07-22T19:26:14.807879972Z] WATCH LIST key=/ rev=2 => rev=2502 kvs=0
    ERRO[2024-07-22T19:26:14.807892698Z] TTL event watch failed: rpc error: code = OutOfRange desc = etcdserver: mvcc: required revision has been compacted
    ```

**Comment by 985492783** [comment]
All right, i was running kine standalone and use etcd client connect to it, just do some technical testing such as lease

**Comment by brandond** [comment]
I will note that kine does leases very different than etcd. Kine's uses the lease ID as the record TTL, and doesn't actually track leases at all internally - all it cares about is using their ID as a TTL. For example, to create a key with a lease duration of 60 seconds (0x3C in hex), just do:
```bash
etcdctl txn <<EOF
mod("/b") = "0"

put --lease=3C /b "bar"

get /b

EOF
```
