### ISSUE TITLE
Clarification on Kine's Lease/TTL implementation

### ISSUE THREAD

**Issue by Yuyz0112** [k3s-io/kine#386]
After going through the code and reading the [comment](https://github.com/k3s-io/kine/issues/311#issuecomment-2246257835) here, I found that Kine's TTL implementation is quite different with etcd.

Since we use lease id as the duration seconds and do not support lease server API, I think any etcd client following the etcd's lease use should not work with Kine.

So my question is who's using Kine's Lease/TTL? Especially, is kube-apiserver using Kine's Lease?

**Comment by brandond** [comment]
The kine implementation is sufficient for her w Kubernetes uses leases. Being good enough for Kubernetes is the only goal of this project.

**Comment by Yuyz0112** [comment]
@brandond Thank you for the guidance!

For others who might be interested in this topic, here is some related code I found:

In kube-apiserver, there is a [store](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go) implementation based on etcd.

It supports TTL for creating objects:

```go
func (s *store) Create(ctx context.Context, key string, obj, out runtime.Object, ttl uint64) error
```

Under the hood, it uses etcd’s lease mechanism to implement TTL:

```go
	if ttl != 0 {
		lease, err = s.leaseManager.GetLease(ctx, int64(ttl))
		if err != nil {
			return err
		}
	}
```

In the [lease manager](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/lease_manager.go), aside from some caching logic, the core implementation uses the etcd lease grant API to obtain a lease ID:

```go
lcr, err := l.client.Lease.Grant(ctx, ttl)
```

In etcd, leases are a resource with complete management capabilities. However, Kine does not implement a full-feature lease server. Instead, Kine implements an ad-hoc lease grant, returning the TTL value as the lease ID.

For kube-apiserver interacting with Kine:
	1.	When granting a lease with TTL, the returned lease ID will be the TTL value.
	2.	When putting a key with the lease ID, the stored event. lease will equal the initial TTL value.

Thus, in the kube-apiserver use case, Kine can rely on the assumption that “event.lease equals the TTL value” and implement cleanup logic using LogStructured.ttl.

**Comment by brandond** [comment]
The apiserver also reuses leases with the same TTL so effectively there is generally only ever one lease.
