### ISSUE TITLE
Allow for custom (propietary) driver

### ISSUE THREAD

**Issue by sargun** [k3s-io/kine#75]
I would like to implement custom drivers with Kine. Unfortunately, it's not trivially for someone to extend Kine without forking. This is because the logic is hard coded: https://github.com/k3s-io/kine/blob/v0.6.0/pkg/endpoint/endpoint.go#L120

I believe it would be fairly easy to move the "inverted" model where the drivers have an init function that registers them (a la how SQL drivers work in Golang). I was curious as to whether people would be interested in this approach?

**Comment by cweagans** [comment]
IMO, it would be sufficient to have an "external" driver type in kine that uses something like https://github.com/hashicorp/go-plugin. Any other db backend could be supported in this manner as long as a clear interface is defined for plugins to implement. Over time, the existing backends could be refactored into this plugin model for consistency. This also allows users to implement support for their desired backend in whatever language they'd like to use - they aren't limited to Go.

**Comment by dereknola** [comment]
There is currently no plans to move to a plugin based version of kine. The team is of course happy to accept PRs that add new DB support.
