### ISSUE TITLE
Heavy usage against MariaDB and unoptimized queries

### ISSUE THREAD

**Issue by Ueland** [k3s-io/kine#80]
I am running a multi master k3s setup on three Pi's to see how it works. But I have noticed that my MariaDB server are getting a lot more traffic than I would expect for such a setup. My MariaDB instance only has k3s/kine traffic at the moment, yet the average for the last 14 days is 101 queries per second. Which is primarily SELECTS (90%), and  INSERTS(10%).

But there are also a rather large amount of queries using table scans and table sorting, which makes it seem that the indexes are not optimal. 

The database itself is only as little as 9MB, so i expected it to fit in nicely in disk cache, but the frequent amount of writes makes that void. I also activated query cache but that is of course also voided quickly due to the updates.

Is this expected behavior? If not, what kind of information is it of interest that i gather?

**Comment by brandond** [comment]
No, that's to be expected. K3s's embedded Kine uses the SQL database as a MVCC, where each modification to the datastore inserts a new row. Kubernetes is pretty much constantly writing things, so a query cache isn't going to be particularly useful. There are definitely a few more optimizations that could be made, but in our experience if performs quite acceptably, even if the query rate is higher than you might see from other applications.

**Comment by Ueland** [comment]
Thanks for the clarification, @brandond!
