### ISSUE TITLE
[feature request] Backup support for kine

### ISSUE THREAD

**Issue by camaeel** [k3s-io/kine#88]
I use k3s with sqlite. But I would like to migrate to embedded etcd. I tried:
`ETCDCTL_API=3 ./etcdctl --endpoints unix:///var/lib/rancher/k3s/server/kine.sock snapshot save snapsht.etcd`

But received error:
```
{"level":"warn","ts":"2021-05-25T22:13:17.511+0200","caller":"clientv3/maintenance.go:210","msg":"failed to receive from snapshot stream; closing","error":"rpc error: code = Unimplemented desc = unknown service etcdserverpb.Maintenance"}
Error: rpc error: code = Unimplemented desc = unknown service etcdserverpb.Maintenance
```

It would be great if this metod is implemented, as migration from one storage to another would be quite easy.

**Comment by afritzler** [comment]
Wouldn't it be better to use the backup facility of the respective SQL database instead of funneling this through etcd's snapshot mechanism? 🤔

**Comment by camaeel** [comment]
Using SQL export won't let load data into etcd.

**Comment by blackandred** [comment]
That would also make easier and universal backup & restore for all kind of databases including sqlite3.

**Comment by brandond** [comment]
K3s will now migrate the data from kine to embedded etcd if started with --cluster-init. From there you can use k3s's etcd snapshot functionality to get a backup file that can be restored to a standalone etcd cluster.

Kine will never support dumping to an etcd compatible snapshot, as it doesn't use the same database format. Only the client interface is compatible.

**Comment by camaeel** [comment]
@brandond Can you point which release added this option? Or if it is not released a commit or Pull Request. Currently I couldn't find docs or source code that provides this.

**Comment by brandond** [comment]
It's in K3s, not kine.
https://github.com/k3s-io/k3s/pull/3231

**Comment by camaeel** [comment]
Thank you. This issue is closed for me then.
